### ISSUE TITLE
Menu features implementation

### ISSUE THREAD

**Issue by admirkrilasevic** [dialob/dialob-parent#101]
The following functionalities are located in the menu and need to be implemented in the new Material composer:
- [x] #114 
- [x] #125
- [x] #111
- [x] #122
- [x] versions dialog (part of #127)
- [x] create tag dialog (part of #127)
- [x] #130
- [x] download form (part of #127)
- [x] #129
